# Generated by Django 4.2.5 on 2023-11-06 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_category_name', models.CharField(max_length=100)),
                ('alt_category_image', models.ImageField(upload_to='category_pic')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_category_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitim_seviyesi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Egitimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitimler_title', models.CharField(max_length=200)),
                ('egitim_icerigi', models.CharField(max_length=200)),
                ('egitim_suresi', models.IntegerField()),
                ('egitim_image', models.ImageField(upload_to='egitim_pic')),
                ('egitim_ucreti', models.IntegerField(null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('egitim_alt_kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMSapp.altcategory')),
                ('egitim_ana_kategori', models.ManyToManyField(blank=True, to='LMSapp.anacategory')),
                ('egitim_seviyesi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMSapp.courselevel')),
                ('egitmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_player_title', models.CharField(max_length=50)),
                ('video_aciklama', models.TextField(max_length=300)),
                ('video_suresi', models.IntegerField()),
                ('video_id', models.CharField(max_length=255, null=True)),
                ('video_egitim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LMSapp.egitimler')),
                ('video_egitmen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('odendiMi', models.BooleanField(default=False)),
                ('egitim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSapp.egitimler')),
                ('ekleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
