# Generated by Django 4.2.5 on 2023-11-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0004_alter_odeme_egitimler'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='odendiMi',
            field=models.BooleanField(default=False),
        ),
    ]
