# Generated by Django 4.2.5 on 2023-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0005_odeme_odendimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='altcategory',
            name='alt_ana_kategori',
            field=models.ManyToManyField(blank=True, to='LMSapp.anacategory'),
        ),
    ]
