# Generated by Django 4.2.5 on 2023-11-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0006_altcategory_alt_ana_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altcategory',
            name='alt_ana_kategori',
        ),
        migrations.AddField(
            model_name='altcategory',
            name='ana_category',
            field=models.ManyToManyField(to='LMSapp.anacategory'),
        ),
        migrations.AlterField(
            model_name='egitimler',
            name='egitim_ana_kategori',
            field=models.ManyToManyField(blank=True, null=True, to='LMSapp.anacategory'),
        ),
    ]
