# Generated by Django 4.2.5 on 2023-11-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0008_alter_altcategory_ana_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_player',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
