# Generated by Django 4.2.3 on 2023-10-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
